POST http://localhost:8081/voucher/seckill
Content-Type: application/json
Authorization: Bearer 754f581ca5224cddb399a11c9f16219e

{
  "shopId": 1,
  "title": "100元代金券",
  "subTitle": "周一至周五均可使用",
  "rules": "全场通用\\n无需预约\\n可无限叠加\\n不兑现、不找零\\n仅限堂食",
  "payValue": 8000,
  "actualValue": 10000,
  "type": 1,
  "stock": 100,
  "beginTime": "2026-03-06T16:00:00",
  "endTime": "2026-03-06T23:00:00"
}
### 1. 获取验证码（替换成你数据库里的手机号）
POST http://localhost:8081/user/code?phone=13456789001
Accept: application/json

### 2. 登录获取 Token（验证码填接口返回的code）
POST http://localhost:8081/user/login
Content-Type: application/json

{
  "phone": "13456789001",
  "code": "955731"
}